services:
  your-service-name:
    env: python
    buildCommand: |
      # حذف أي تثبيتات موجودة لـ WeasyPrint و pydyf
      pip uninstall weasyprint pydyf -y
      # حذف البيئة الافتراضية القديمة بالكامل
      rm -rf .venv
      # إنشاء بيئة جديدة
      python -m venv .venv
      . .venv/bin/activate
      # تحديث pip وتثبيت الحزم بدقة
      pip install --upgrade pip
      pip install -r requirements.txt --force-reinstall --no-cache-dir

services:
  - type: static
    name: valuation-report
    buildCommand: echo "Static HTML - No build needed"
    publish: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 